wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685435331.45418
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 4
      - 5
